CXX = g++
INCLUDES += -I /
INCLUDES += -I shapes/Inc/

SOURCES += main.cpp
SOURCES += shapes/Src/Shape.cpp
SOURCES += shapes/Src/Triangle.cpp
SOURCES += shapes/Src/Circle.cpp

all: run

run:
	$(CXX) $(INCLUDES) -o run $(SOURCES)

clean:
	rm -rf run

