CXX = g++
INCLUDES += -I /

SOURCES += main.cpp
SOURCES += Car.cpp
SOURCES += Truck.cpp
SOURCES += Sedan.cpp
SOURCES += Suv.cpp

all: run

run:
	$(CXX) $(INCLUDES) -o run $(SOURCES)

clean:
	rm -rf run

